name: Build and Upload CV
on:
  push:
    tags:
      - '*'
jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Render CV
        run: nix-shell --run "make cv"

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: output/*.pdf
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Prepare HTML for GitHub Pages
        run: |
          mkdir publish
          cp output/*.html publish/

      - name: Deploy HTML to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./publish
          publish_branch: gh-pages
          force_orphan: true